# Generated by Django 4.2.2 on 2023-06-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ageMissing',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='city unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='firstName',
            field=models.CharField(default='name unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='gender unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='lastName',
            field=models.CharField(default='name unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='race',
            field=models.CharField(default='race unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default='state unknown', max_length=50),
        ),
    ]
