# Generated by Django 4.2.2 on 2023-06-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingapp', '0002_person_agemissing_person_city_person_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dateMissing',
            field=models.CharField(default='name date', max_length=50),
        ),
    ]
